// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SteeringModeType.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SteeringModeType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace lunabotics {

namespace {

const ::google::protobuf::EnumDescriptor* SteeringModeType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SteeringModeType_2eproto() {
  protobuf_AddDesc_SteeringModeType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SteeringModeType.proto");
  GOOGLE_CHECK(file != NULL);
  SteeringModeType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SteeringModeType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_SteeringModeType_2eproto() {
}

void protobuf_AddDesc_SteeringModeType_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026SteeringModeType.proto\022\nlunabotics*=\n\020"
    "SteeringModeType\022\r\n\tACKERMANN\020\001\022\020\n\014TURN_"
    "IN_SPOT\020\002\022\010\n\004CRAB\020\003", 99);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SteeringModeType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SteeringModeType_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SteeringModeType_2eproto {
  StaticDescriptorInitializer_SteeringModeType_2eproto() {
    protobuf_AddDesc_SteeringModeType_2eproto();
  }
} static_descriptor_initializer_SteeringModeType_2eproto_;
const ::google::protobuf::EnumDescriptor* SteeringModeType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SteeringModeType_descriptor_;
}
bool SteeringModeType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace lunabotics

// @@protoc_insertion_point(global_scope)
